name: Run jq
author: emptylight
description: Run jq on input file and return jq outputs

inputs:
  data:
    description: Run jq on this file.
    required: true

  filter:
    description: The jq selector. see https://jqlang.org/manual/#basic-filters
    required: true

  raw:
    default: 'true'
    description: Raw output, not json string. In complex output, set to false and manually parse the JSON string.
    required: false

  options:
    description: The options to append to jq command. see https://jqlang.org/manual/#invoking-jq
    required: false

outputs:
  result:
    description: The jq result.
    value: ${{ steps.runjq.outputs.result }}

runs:
  # For more on composite actions, see:
  # https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
  using: composite
  steps:
    - id: runjq
      shell: bash
      run: |
        RAW_FLAG=""
        if [ "${{ inputs.raw }}" == "true" ]; then
          RAW_FLAG="-r"
        fi

        OPTIONS=""
        if [ -n "${{ inputs.options }}" ]; then
          OPTIONS="${{ inputs.options }}"
        fi

        INPUT_DATA='${{ inputs.data }}'

        # 检查是否为合法 JSON 字符串
        if echo "$INPUT_DATA" | jq . > /dev/null 2>&1; then
          # 是合法的 JSON 字符串
          RESULT=$(echo "$INPUT_DATA" | jq $RAW_FLAG $OPTIONS '${{ inputs.filter }}')
        # 检查是否为存在的文件
        elif [ -f "$INPUT_DATA" ]; then
          # 是存在的文件
          RESULT=$(jq $RAW_FLAG $OPTIONS '${{ inputs.filter }}' '$INPUT_DATA')
        else
          echo "::error::Input '$INPUT_DATA' is neither a valid JSON string nor an existing file."
          exit 1
        fi

        echo "result=$RESULT" >> $GITHUB_OUTPUT
