name: Test

on:
  push:
    branches:
      - main
    paths:
      - action.yml
      - .github/workflows/test.yml
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-26, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: 'Step 1: Get metadata'
        id: step1
        uses: ./
        with:
          data: metadata.json
          filter: .version

      - name: 'Step 2: Get json string data'
        id: step2
        uses: ./
        with:
          data: '{"name": "query result"}'
          filter: .name

      - name: 'Step 3: Get subfolder file data'
        id: step3
        uses: ./
        with:
          data: test/theme.json
          filter: .version

      - name: 'Step 4: Sort json string data'
        id: step4
        uses: ./
        with:
          data: '{"c":3,"b":2,"a":1}'
          filter: .
          options: --indent 0 --sort-keys

      - name: 'Step 5: Multiline output'
        id: step5
        uses: ./
        with:
          data: '{"items": ["a", "b", "c"]}'
          filter: '.items[]'

      - name: 'Step 6: Null input'
        id: step6
        uses: ./
        with:
          data: 'null'
          filter: '{a:1}'
          options: --compact-output

      - name: Show output
        run: |
          echo Step 1: ${{ steps.step1.outputs.result }}
          echo Step 2: ${{ steps.step2.outputs.result }}
          echo Step 3: ${{ steps.step3.outputs.result }}
          echo Step 4: ${{ steps.step4.outputs.result }}
          echo Step 5 is multiline: ${{ steps.step5.outputs.multiline }}
          step5_results="${{ steps.step5.outputs.result }}"
          for result in $step5_results; do
            echo "Step 5: $result"
          done
          echo Step 6: ${{ steps.step6.outputs.result }}
